# Generated by Django 5.2.5 on 2025-08-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_purchaseorderitem_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='note',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='note',
        ),
        migrations.AddField(
            model_name='stock',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
