# Generated by Django 5.2.5 on 2025-08-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20250829_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('demo_unit', 'Demo Unit'), ('bstock', 'B-Stock')], default='new', max_length=20),
        ),
    ]
