# Generated by Django 5.2.5 on 2025-09-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_purchaseorder_creating_store_store_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Store or warehouse name', max_length=200),
        ),
    ]
