# Generated by Django 5.2.5 on 2025-09-09 06:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_alter_stockhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('admin', 'Admin'), ('owner', 'Owner'), ('logistics', 'Logistics'), ('warehouse', 'Warehouse'), ('stocktake_manager', 'Stock Take Manager'), ('warehouse_boy', 'Warehouse Boy'), ('sales', 'Sales'), ('accountant', 'Accountant')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text="Manufacturer's invoice number", max_length=100)),
                ('invoice_date', models.DateField(help_text='Date on the invoice from manufacturer')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('invoice_amount_exc', models.DecimalField(decimal_places=2, help_text='Invoice amount excluding GST', max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, help_text='GST amount on invoice', max_digits=12)),
                ('invoice_total', models.DecimalField(decimal_places=2, help_text='Total invoice amount including GST', max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, help_text='Outstanding amount to be paid', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about the invoice', null=True)),
                ('invoice_file', models.FileField(blank=True, help_text='Scanned copy of the invoice', null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='stock.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('purchase_order', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(help_text='Payment reference number (check number, transfer ID, etc.)', max_length=100)),
                ('payment_date', models.DateField(help_text='Date payment was made')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('other', 'Other')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('bank_details', models.TextField(blank=True, help_text='Bank transfer details, check details, etc.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment', null=True)),
                ('receipt_file', models.FileField(blank=True, help_text='Receipt or proof of payment', null=True, upload_to='payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stock.invoice')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
