# Generated by Django 5.2.5 on 2025-09-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_alter_stockhistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
        migrations.AddField(
            model_name='store',
            name='abn',
            field=models.CharField(blank=True, help_text='Australian Business Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL link to business logo image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, help_text='Company website URL', max_length=500, null=True),
        ),
    ]
