# Generated by Django 5.2.5 on 2025-09-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_store_fields_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='abn',
            field=models.CharField(blank=True, help_text='Australian Business Number', max_length=20, null=True),
        ),
    ]
