# Generated by Django 5.2.5 on 2025-09-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_manufacturer_abn_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='order_email',
            field=models.EmailField(blank=True, help_text='Email address for purchase order confirmations', max_length=255, null=True),
        ),
    ]
