# Generated by Django 5.2.5 on 2025-09-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_remove_stock_image_stock_image_url_stock_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-last_updated', '-timestamp', '-date']},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-completed_at', '-approved_at', '-created_at']},
        ),
    ]
