# Generated by Django 5.2.5 on 2025-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_merge_20250909_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Customer delivery address for dropship orders', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for dropship orders', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_order_number',
            field=models.CharField(blank=True, help_text='Customer order reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone number', max_length=20, null=True),
        ),
    ]
