# Generated by Django 5.2.5 on 2025-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_add_zoho_product_fields'),
    ]

    operations = [
        # Fix the item_name field length in Stock model
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        # Also fix item_name in StockHistory model
        migrations.AlterField(
            model_name='stockhistory',
            name='item_name',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
    ]
