# Generated by Django 5.2.5 on 2025-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_alter_item_name_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('demo_unit', 'Demo Unit'), ('bstock', 'B-Stock'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse_name',
            field=models.CharField(blank=True, db_index=True, help_text='Warehouse name from Zoho', max_length=200, null=True),
        ),
    ]
