// Mock data for development when backend is not available

export const mockUser = {
  id: 1,
  username: 'admin',
  email: 'admin@example.com',
  first_name: 'Admin',
  last_name: 'User',
  full_name: 'Admin User',
  is_active: true,
  date_joined: '2024-01-01T00:00:00Z',
  role: {
    id: 1,
    user: 1,
    role: 'admin' as const,
    created_at: '2024-01-01T00:00:00Z',
  },
};

export const mockStocktakes = {
  count: 3,
  total_pages: 1,
  current_page: 1,
  page_size: 20,
  links: { next: null, previous: null },
  results: [
    {
      id: 1,
      name: 'Monthly Stock Count - December 2024',
      description: 'Regular monthly stock counting for all locations',
      status: 'completed',
      location: { id: 1, name: 'Main Warehouse' },
      created_by: mockUser,
      created_at: '2024-12-01T09:00:00Z',
      started_at: '2024-12-01T10:00:00Z',
      completed_at: '2024-12-01T16:00:00Z',
      items: [],
      total_items: 150,
      items_counted: 150,
      items_pending: 0,
      total_variance: -5,
      progress_percentage: 100,
    },
    {
      id: 2,
      name: 'Year-end Stocktake 2024',
      description: 'Annual stock verification for accounting purposes',
      status: 'in_progress',
      location: null,
      created_by: mockUser,
      created_at: '2024-12-20T08:00:00Z',
      started_at: '2024-12-20T09:00:00Z',
      completed_at: null,
      items: [],
      total_items: 500,
      items_counted: 320,
      items_pending: 180,
      total_variance: 0,
      progress_percentage: 64,
    },
    {
      id: 3,
      name: 'Electronics Section Count',
      description: 'Focused count on electronics inventory',
      status: 'planning',
      location: { id: 2, name: 'Electronics Store' },
      created_by: mockUser,
      created_at: '2024-12-25T10:00:00Z',
      started_at: null,
      completed_at: null,
      items: [],
      total_items: 75,
      items_counted: 0,
      items_pending: 75,
      total_variance: 0,
      progress_percentage: 0,
    },
  ],
};

export const mockPurchaseOrders = {
  count: 4,
  total_pages: 1,
  current_page: 1,
  page_size: 20,
  links: { next: null, previous: null },
  results: [
    {
      id: 1,
      po_number: 'PO-2024-001',
      supplier_name: 'Tech Supplies Inc.',
      supplier_email: 'orders@techsupplies.com',
      supplier_phone: '+1 555-0123',
      status: 'received',
      order_date: '2024-11-15',
      expected_delivery_date: '2024-11-25',
      delivery_date: '2024-11-24',
      subtotal: 5000.00,
      tax_amount: 500.00,
      total_amount: 5500.00,
      created_by: mockUser,
      created_at: '2024-11-15T14:30:00Z',
      sent_at: '2024-11-15T15:00:00Z',
      received_at: '2024-11-24T11:00:00Z',
      items: [],
      total_items: 15,
      items_received: 15,
      items_pending: 0,
      is_fully_received: true,
      is_overdue: false,
    },
    {
      id: 2,
      po_number: 'PO-2024-002',
      supplier_name: 'Office Equipment Ltd.',
      supplier_email: 'sales@officeequip.com',
      supplier_phone: '+1 555-0456',
      status: 'partially_received',
      order_date: '2024-12-10',
      expected_delivery_date: '2024-12-20',
      delivery_date: null,
      subtotal: 3200.00,
      tax_amount: 320.00,
      total_amount: 3520.00,
      created_by: mockUser,
      created_at: '2024-12-10T09:15:00Z',
      sent_at: '2024-12-10T10:00:00Z',
      received_at: null,
      items: [],
      total_items: 8,
      items_received: 5,
      items_pending: 3,
      is_fully_received: false,
      is_overdue: false,
    },
    {
      id: 3,
      po_number: 'PO-2024-003',
      supplier_name: 'Industrial Parts Co.',
      supplier_email: 'orders@indparts.com',
      status: 'sent',
      order_date: '2024-12-22',
      expected_delivery_date: '2025-01-05',
      delivery_date: null,
      subtotal: 8750.00,
      tax_amount: 875.00,
      total_amount: 9625.00,
      created_by: mockUser,
      created_at: '2024-12-22T16:45:00Z',
      sent_at: '2024-12-22T17:00:00Z',
      items: [],
      total_items: 25,
      items_received: 0,
      items_pending: 25,
      is_fully_received: false,
      is_overdue: false,
    },
    {
      id: 4,
      po_number: 'PO-2024-004',
      supplier_name: 'Global Manufacturers',
      supplier_email: 'procurement@globalmfg.com',
      status: 'draft',
      order_date: '2024-12-26',
      expected_delivery_date: '2025-01-15',
      delivery_date: null,
      subtotal: 12000.00,
      tax_amount: 1200.00,
      total_amount: 13200.00,
      created_by: mockUser,
      created_at: '2024-12-26T08:00:00Z',
      sent_at: null,
      items: [],
      total_items: 30,
      items_received: 0,
      items_pending: 30,
      is_fully_received: false,
      is_overdue: false,
    },
  ],
};

export const mockStores = {
  count: 3,
  results: [
    { id: 1, name: 'Main Warehouse', designation: 'warehouse', location: 'Building A' },
    { id: 2, name: 'Electronics Store', designation: 'store', location: 'Mall Location' },
    { id: 3, name: 'Distribution Center', designation: 'warehouse', location: 'Industrial Park' },
  ],
};