# Generated by Django 5.2.5 on 2025-08-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_purchaseorder_options_remove_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.CharField(help_text='Product name or description', max_length=255),
        ),
    ]
