# Generated by Django 5.2.5 on 2025-08-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_purchaseorderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
