# Generated by Django 5.2.5 on 2025-08-25 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_purchaseorderitem_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
