# Generated by Django 5.2.5 on 2025-08-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_purchaseorderreceiving_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
