# Generated by Django 5.2.5 on 2025-08-29 02:18

from django.db import migrations


def set_default_condition(apps, schema_editor):
    """Set default condition for existing stock items"""
    Stock = apps.get_model('stock', 'Stock')
    # Set all existing items to 'brand_new' if they don't have a condition
    Stock.objects.filter(condition__isnull=True).update(condition='brand_new')
    Stock.objects.filter(condition='').update(condition='brand_new')


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_stock_committed_quantity_stock_condition_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_condition),
    ]
