# Generated by Django 5.2.5 on 2025-08-29 03:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_stock_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='aisle',
            field=models.CharField(blank=True, help_text='Specific aisle or section within the store', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Store location where this item is kept', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.store'),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('from_aisle', models.CharField(blank=True, max_length=50, null=True)),
                ('to_aisle', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_reason', models.CharField(help_text='Reason for transfer (e.g., customer collection, restock)', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='stock.store')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='stock.stock')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='stock.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
