# Generated by Django 5.2.5 on 2025-08-29 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_stock_aisle_stock_location_stocktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name (for collection transfers)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('customer_collection', 'Customer Collection'), ('general', 'General Transfer')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('awaiting_collection', 'Awaiting Customer Collection'), ('collected', 'Customer Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
