# Generated by Django 5.2.5 on 2025-08-29 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_stocktransfer_collected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('aisle', models.CharField(blank=True, help_text='Specific aisle or section within the store', max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='stock.stock')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.store')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('stock', 'store')},
            },
        ),
    ]
