# Generated by Django 5.2.5 on 2025-08-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_stocklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(choices=[('audio_junction_newcastle', 'Audio Junction Store - Newcastle'), ('digital_cinema_auburn', 'Digital Cinema Store - Auburn'), ('instyle_dural', 'Instyle Store - Dural'), ('silverwater_warehouse', 'Silverwater Warehouse'), ('auburn_warehouse', 'Auburn Warehouse')], max_length=200),
        ),
    ]
