# Generated by Django 5.2.5 on 2025-08-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_add_store_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
