# Generated by Django 5.2.5 on 2025-08-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_make_category_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, help_text='Store contact email', max_length=255, null=True),
        ),
    ]
