# Generated by Django 5.2.5 on 2025-09-02 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_stockreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_reference', models.CharField(help_text='Unique audit reference number', max_length=100, unique=True)),
                ('audit_type', models.CharField(choices=[('full', 'Full Stock Audit'), ('partial', 'Partial Audit'), ('cycle', 'Cycle Count'), ('location', 'Location Audit'), ('category', 'Category Audit'), ('spot_check', 'Spot Check')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='planned', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('total_items_planned', models.IntegerField(default=0)),
                ('total_items_counted', models.IntegerField(default=0)),
                ('items_with_variances', models.IntegerField(default=0)),
                ('total_variance_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_audits', to=settings.AUTH_USER_MODEL)),
                ('assigned_auditors', models.ManyToManyField(blank=True, related_name='assigned_audits', to=settings.AUTH_USER_MODEL)),
                ('audit_categories', models.ManyToManyField(blank=True, help_text='Categories to be audited', to='stock.category')),
                ('audit_locations', models.ManyToManyField(blank=True, help_text='Locations to be audited', to='stock.store')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Audit',
                'verbose_name_plural': 'Stock Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(help_text='System quantity at time of audit')),
                ('committed_quantity', models.IntegerField(default=0, help_text='Committed quantity at time of audit')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Reserved quantity at time of audit')),
                ('physical_count', models.IntegerField(blank=True, help_text='Physical count during audit', null=True)),
                ('variance_quantity', models.IntegerField(default=0, help_text='Variance (Physical - System)')),
                ('count_date', models.DateTimeField(blank=True, null=True)),
                ('variance_reason', models.CharField(blank=True, choices=[('shrinkage', 'Shrinkage'), ('damage', 'Damage/Loss'), ('theft', 'Theft'), ('counting_error', 'Counting Error'), ('system_error', 'System Error'), ('transfer_unrecorded', 'Transfer Not Recorded'), ('receiving_error', 'Receiving Error'), ('other', 'Other')], max_length=30, null=True)),
                ('variance_notes', models.TextField(blank=True, null=True)),
                ('adjustment_applied', models.BooleanField(default=False)),
                ('adjustment_date', models.DateTimeField(blank=True, null=True)),
                ('audit_location', models.CharField(blank=True, max_length=100, null=True)),
                ('audit_aisle', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='stock.stockaudit')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_items', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='stock.stock')),
            ],
            options={
                'verbose_name': 'Audit Item',
                'verbose_name_plural': 'Audit Items',
                'ordering': ['stock__item_name'],
                'unique_together': {('audit', 'stock')},
            },
        ),
    ]
