# Generated by Django 5.2.5 on 2025-09-04 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_add_missing_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='creating_store',
            field=models.ForeignKey(blank=True, help_text='Store that created this purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to='stock.store', verbose_name='Creating Store'),
        ),
        migrations.AddField(
            model_name='store',
            name='designation',
            field=models.CharField(choices=[('store', 'Store'), ('warehouse', 'Warehouse')], default='store', help_text='Designate as Store or Warehouse', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo for this store/warehouse', null=True, upload_to='store_logos/'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(help_text='Delivery location where items will be received and added to inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchase_orders', to='stock.store', verbose_name='Delivery Location'),
        ),
    ]
