# Generated by Django 5.2.5 on 2025-09-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('admin', 'Admin'), ('owner', 'Owner'), ('logistics', 'Logistics'), ('warehouse', 'Warehouse'), ('sales', 'Sales')], default='pending', max_length=20),
        ),
    ]
