# Generated by Django 5.2.5 on 2025-09-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('admin', 'Admin'), ('owner', 'Owner'), ('logistics', 'Logistics'), ('warehouse', 'Warehouse'), ('stocktake_manager', 'Stock Take Manager'), ('warehouse_boy', 'Warehouse Boy'), ('sales', 'Sales')], default='pending', max_length=20),
        ),
    ]
