# Generated by Django 5.2.5 on 2025-09-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-last_updated']},
        ),
    ]
