# Generated by Django 5.2.5 on 2025-09-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_alter_purchaseorder_options_alter_stock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['-timestamp', '-last_updated']},
        ),
    ]
