# Generated by Django 5.2.5 on 2025-09-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_store_order_email_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
        migrations.AddField(
            model_name='stock',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to display an image of the item', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - unique identifier for this item', max_length=100, null=True, unique=True),
        ),
    ]
