# Generated by Django 5.2.5 on 2025-09-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_add_payment_tracking_system'),
        ('stock', '0041_alter_purchaseorder_options_alter_stock_options_and_more'),
    ]

    operations = [
    ]
