# Generated by Django 5.2.5 on 2025-09-15 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_merge_20250909_0702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='deliveryperson',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('purchase_order_created', 'Purchase Order Created'), ('purchase_order_confirmed', 'Purchase Order Confirmed'), ('stock_transfer_initiated', 'Stock Transfer Initiated'), ('stock_transfer_completed', 'Stock Transfer Completed'), ('stock_committed', 'Stock Committed'), ('stock_received', 'Stock Received'), ('po_items_received', 'Purchase Order Items Received'), ('stock_audit_started', 'Stock Audit Started'), ('stock_audit_completed', 'Stock Audit Completed'), ('invoice_created', 'Invoice Created'), ('payment_made', 'Payment Made'), ('stock_low', 'Low Stock Alert'), ('reservation_created', 'Stock Reservation Created'), ('reservation_expired', 'Stock Reservation Expired')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'purchase_order', 'stock_transfer')", max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='stock_notif_recipie_316c7f_idx'), models.Index(fields=['recipient', 'notification_type'], name='stock_notif_recipie_cf176e_idx')],
            },
        ),
    ]
