# Generated by Django 5.2.5 on 2025-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_add_notification_model'),
    ]

    operations = [
        # Add new fields to Product model (stock_product table)
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True, blank=True, null=True, help_text="Stock Keeping Unit - unique identifier"),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=100, blank=True, null=True, help_text="Universal Product Code"),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(max_length=100, blank=True, null=True, help_text="European Article Number"),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=100, blank=True, null=True, help_text="International Standard Book Number"),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(max_length=100, blank=True, null=True, help_text="Manufacturer part number"),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200, blank=True, null=True, help_text="Product brand"),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=200, blank=True, null=True, help_text="Product manufacturer"),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_description',
            field=models.TextField(blank=True, null=True, help_text="Sales description from Zoho"),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=50, blank=True, null=True, help_text="Product type (goods/service)"),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=50, blank=True, null=True, help_text="Unit of measurement (box/pair/etc)"),
        ),
        # Physical dimensions
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, help_text="Package weight"),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, help_text="Package length"),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, help_text="Package width"),
        ),
        migrations.AddField(
            model_name='product',
            name='package_height',
            field=models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, help_text="Package height"),
        ),
        migrations.AddField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(max_length=10, blank=True, null=True, help_text="Dimension unit (cm/inch)"),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(max_length=10, blank=True, null=True, help_text="Weight unit (kg/lb)"),
        ),
        # Zoho integration fields
        migrations.AddField(
            model_name='product',
            name='zoho_item_id',
            field=models.CharField(max_length=100, unique=True, blank=True, null=True, help_text="Zoho Item ID"),
        ),
        migrations.AddField(
            model_name='product',
            name='zoho_created_time',
            field=models.DateTimeField(blank=True, null=True, help_text="Created time from Zoho"),
        ),
        migrations.AddField(
            model_name='product',
            name='zoho_last_modified',
            field=models.DateTimeField(blank=True, null=True, help_text="Last modified time from Zoho"),
        ),
        # Add new fields to Stock model (stock_stock table)
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(
                to='stock.Product',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                related_name='stock_items',
                help_text="Link to product catalog"
            ),
        ),
        migrations.AddField(
            model_name='stock',
            name='opening_stock',
            field=models.IntegerField(default=0, blank=True, null=True, help_text="Opening stock from Zoho"),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_on_hand',
            field=models.IntegerField(default=0, blank=True, null=True, help_text="Stock on hand from Zoho"),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse_name',
            field=models.CharField(max_length=200, blank=True, null=True, help_text="Warehouse name from Zoho"),
        ),
        # Update Stock model condition choices to include new conditions
        migrations.AlterField(
            model_name='stock',
            name='condition',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('new', 'New'),
                    ('demo_unit', 'Demo Unit'),
                    ('bstock', 'B-Stock'),
                    ('open_box', 'Open Box'),
                    ('refurbished', 'Refurbished'),
                ],
                default='new'
            ),
        ),
    ]
