# Generated by Django 5.2.5 on 2025-12-22 05:00

from django.db import migrations, models, connection


def remove_item_name_indexes(apps, schema_editor):
    """Remove any indexes on item_name before converting to TextField"""
    with connection.cursor() as cursor:
        # Drop index on stock_stock.item_name if exists
        cursor.execute("""
            SELECT DISTINCT index_name
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'stock_stock'
            AND column_name = 'item_name'
            AND index_name != 'PRIMARY'
        """)
        for row in cursor.fetchall():
            cursor.execute(f"ALTER TABLE stock_stock DROP INDEX `{row[0]}`")

        # Drop index on stock_stockhistory.item_name if exists
        cursor.execute("""
            SELECT DISTINCT index_name
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'stock_stockhistory'
            AND column_name = 'item_name'
            AND index_name != 'PRIMARY'
        """)
        for row in cursor.fetchall():
            cursor.execute(f"ALTER TABLE stock_stockhistory DROP INDEX `{row[0]}`")


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_fix_item_name_length'),
    ]

    operations = [
        migrations.RunPython(remove_item_name_indexes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
