# Generated by Django 5.2.5 on 2025-12-22 05:44

from django.db import migrations, models, connection


def remove_duplicate_indexes(apps, schema_editor):
    """Remove any existing indexes before AlterField tries to add them"""
    with connection.cursor() as cursor:
        # Remove existing indexes on condition field
        cursor.execute("""
            SELECT DISTINCT index_name FROM information_schema.statistics
            WHERE table_schema = DATABASE() AND table_name = 'stock_stock'
            AND column_name = 'condition' AND index_name != 'PRIMARY'
        """)
        for row in cursor.fetchall():
            try:
                cursor.execute(f"ALTER TABLE stock_stock DROP INDEX `{row[0]}`")
            except:
                pass

        # Remove existing indexes on warehouse_name field
        cursor.execute("""
            SELECT DISTINCT index_name FROM information_schema.statistics
            WHERE table_schema = DATABASE() AND table_name = 'stock_stock'
            AND column_name = 'warehouse_name' AND index_name != 'PRIMARY'
        """)
        for row in cursor.fetchall():
            try:
                cursor.execute(f"ALTER TABLE stock_stock DROP INDEX `{row[0]}`")
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_alter_item_name_to_textfield'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_indexes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stock',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('demo_unit', 'Demo Unit'), ('bstock', 'B-Stock'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse_name',
            field=models.CharField(blank=True, db_index=True, help_text='Warehouse name from Zoho', max_length=200, null=True),
        ),
    ]
