# Generated by Django 5.2.5 on 2025-12-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_comprehensive_index_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
