# Generated by Django 5.2.5 on 2025-12-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_purchaseorder_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('sent', 'Sent to Manufacturer'), ('confirmed', 'Confirmed'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
